appEditorial/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'appEditorial'

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('', views.home),
	url('home/', views.home, name = 'home'),
	url('catalogo/', views.catalogo, name = 'catalogo'),
    url(r'catalogo$', views.catalogo_filtro, name = 'catalogo_filtro'),
    url(r'editar$', views.editar_libros, name = 'editar_libros'),
    url(r'editar_libro$', views.editar_libro, name = 'editar_libro'),
    url(r'eliminar_libro$', views.eliminar_libro, name = 'eliminar_libro'),
    url('autores/', views.autores, name = 'autores'),
    url('about/', views.about, name = 'about'),
    url('contacto/', views.contacto, name = 'contacto'),
    url('gestionLibros/', views.gestionarLibros, name = 'gestionLibros'),
    url('agregar_libro/', views.agregar_libro, name = 'agregar_libro'),
    url('editar_libro/', views.editar_libro, name = 'editar_libro'),
    url('agregar_autor/', views.agregar_autor, name = 'agregar_autor'),
    url('agregar_editorial/', views.agregar_editorial, name = 'agregar_editorial'),
    path('api/libros/', views.API_libros.as_view()),
    path('api/libros/id/<id>/', views.API_libro_por_id.as_view()),
    path('api/libros/titulo/<titulo>/', views.API_libro_por_titulo.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

appRegistro/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'appRegistro'

urlpatterns = [
    url('index/', views.index, name = 'index'),
    url('login/', views.usuario_login, name = 'login'),
    url('logout/', views.usuario_logout, name = 'logout'),
    url('registro/', views.registrar, name = 'registro'),
    url('gestionEditorial/', views.gestionarEditorial, name = 'gestionEditorial'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='recuperacion/password_reset_form.html',
             subject_template_name='recuperacion/password_reset_subject.txt',
             email_template_name='recuperacion/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='recuperacion/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='recuperacion/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='recuperacion/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

editorial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mantenedor/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sicmundus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('appEditorial.urls')),
    path('admin/', admin.site.urls),
    path('ad/', include('appRegistro.urls')),
    url('ad/', include('django.contrib.auth.urls')),
]

appRegistro/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class PerfilUsuario(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	run = models.CharField(max_length=20)
	nacimiento = models.DateField(auto_now=False, auto_now_add=False)
	telefono = models.CharField(max_length=50)
	region = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=50)
	comuna = models.CharField(max_length=50)
	vivienda = models.CharField(max_length=50)

	def __str__(self):
		return self.run


appRegistro/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import PerfilUsuario


class PerfilUsuarioForm(ModelForm):
    class Meta():
        model = PerfilUsuario
        fields = [
            'run',
            'nacimiento',
            'telefono',
            'region',
            'ciudad',
            'comuna',
            'vivienda'
        ]
        labels = {
            'run': 'RUN',
            'nacimiento': 'Fecha de Nacimiento',
            'telefono': 'Teléfono',
            'region': 'Región',
            'ciudad': 'Ciudad',
            'comuna': 'Comuna',
            'vivienda': 'Vivienda'
        }
        widgets = {
            'nacimiento': forms.SelectDateWidget(
                years=(range(2020, 1900, -1)))
        }

    def __init__(self, *args, **kwargs):
        super(PerfilUsuarioForm, self).__init__(*args, **kwargs)
        self.fields['run'].widget.attrs.update({'class': 'form-control'})
        self.fields['nacimiento'].widget.attrs.update({'class': 'form-control datepicker'})
        self.fields['telefono'].widget.attrs.update({'class': 'form-control'})
        self.fields['region'].widget.attrs.update({'class': 'form-control'})
        self.fields['ciudad'].widget.attrs.update({'class': 'form-control'})
        self.fields['comuna'].widget.attrs.update({'class': 'form-control'})
        self.fields['vivienda'].widget.attrs.update({'class': 'form-control'})


class RegistrarForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',
            'first_name',
            'last_name'
        ]
        labels = {
            'username': 'Nombre de Usuario',
            'password': 'Contraseña',
            'email': 'Correo',
            'first_name': 'Nombre',
            'last_name': 'Apellido'
        }
        help_texts = {
            'username': ''
        }


    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})

appRegistro/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages

from .forms import PerfilUsuarioForm, RegistrarForm
from .models import PerfilUsuario
from appEditorial import templates

# Create your views here.
def index(request):
	return render(request, "appRegistro/index.html")


def usuario_logout(request):
	if request.user.is_superuser:
		logout(request)
		return HttpResponseRedirect(reverse('appRegistro:login'))
	else:
		logout(request)
		return HttpResponseRedirect(reverse('appEditorial:home'))


def usuario_login(request):
	if request.user.is_authenticated:
		if request.user.is_superuser:
			return HttpResponseRedirect(reverse('appRegistro:index'))
		else:
			return HttpResponseRedirect(reverse('appEditorial:home'))
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')
			user = authenticate(username=username, password=password)
			if user:
				if not user.is_active:
					messages.info(request, 'Tu cuenta esta inactiva')
					return HttpResponseRedirect(reverse('appRegistro:login'))
				elif user.is_active and user.is_superuser:
					login(request, user)
					return HttpResponseRedirect(reverse('appRegistro:index'))
				elif user.is_active and not user.is_superuser:
					login(request, user)
					return HttpResponseRedirect(reverse('appEditorial:home'))
			else:
				messages.info(request, 'Clave o Contraseña inválidas')
				return HttpResponseRedirect(reverse('appRegistro:login'))
		else:
			return render(request, 'appRegistro/login.html')


def registrar(request):
	if request.method == 'POST':
		print("Estoy intentando ingresar un usuario")
		user_form = RegistrarForm(data=request.POST)
		profile_form = PerfilUsuarioForm(data=request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			messages.info(request, 'Usuario Registrado Correctamente')
			return HttpResponseRedirect(reverse('appRegistro:login'))
		else:
			return HttpResponse("Datos invalidos.")
	else:
		user_form = RegistrarForm()
		profile_form = PerfilUsuarioForm()

	return render(request, 'appRegistro/registro.html',
					{'user_form': user_form,
					'profile_form': profile_form})


def gestionarEditorial(request):
	return render(request, 'appEditorial/mantenedor_home.html')



appRegistro/templates/appRegistro/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!--Bootstrap con Jquery -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/message.js' %}"></script>
        <!--CSS propio-->
        <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
        <!-- Font awesome -->
        <script src="{% static 'fontawesome/js/all.js' %}"></script>
        <title>
        {% block titulo %}
        {% endblock titulo %}
        </title>
    </head>
    <body>
        <!-- Header -->
        <header>
            <div class="flex-grow-1">
                <div class="header-chico">
                    <ul class="nav d-flex justify-content-end ">
                        {% if not request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_editorial %}{% endblock nav_class_editorial %}" href="{% url 'appEditorial:home' %}">Editorial Sic Mundus</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_login %}{% endblock nav_class_login %}" href="{% url 'appRegistro:login' %}">Login</a>
                            </li>
                        {% else %}
                            {% if request.user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link {% block nav_class_home %}{% endblock nav_class_home %}" href="{% url 'appRegistro:index' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% block nav_class_gestion %}{% endblock nav_class_gestion %}" href="{% url 'appRegistro:gestionEditorial' %}">Gestion Editorial</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {% block nav_class_logout %}{% endblock nav_class_logout %}" href="{% url 'appRegistro:logout' %}">Cerrar Sesion</a>
                                </li>
                            {% endif %}
                        {% endif %}
                        <li class="hamburguesa">
                            <a href="javascript:void(0);" class=icon onclick="toggleMenu()"><i class="fas fa-bars fa-3x"></i></a>
                        </li>
                    </ul>
                </div>
                {% block nav_content %}{% endblock nav_content %}
            </div>
        </header>
        <div id="contenedor-dos">
            {% block content %}
            {% endblock content %}
            <br>
        </div>
        <footer class="d-flex flex-wrap footer">
            <div class="d-flex flex-wrap p-2 logo-footer">
                <img id="logo_footer" src="{% static 'img/logo.png' %}" alt="logo-editorial">
            </div>
        </footer>
        <script src="/js/hamburguesa.js"></script>
    </body>
</html>

appRegistro/templates/appRegistro/index.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block nav_class_home %}active{% endblock nav_class_home %}
{% block content %}
    <div id="bienvenida" class="subheader">
        <h1 class="titulo hepta-bold">Bienvenido al mantenedor Editorial Sic Mundus</h1>
    </div>
    <div class="desc d-flex justify-content-center">
        <p>Aquí podrás agregar nuevos libros, buscar aplicando filtros, editar su información y/o eliminarlos.</p>
    </div>
{% endblock content %}

appRegistro/templates/appRegistro/login.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block titulo %}Iniciar sesion{% endblock titulo %}
{% block nav_class_login %}active{% endblock nav_class_login %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p class="mensaje">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <div class="login p-2">
        <h1 class="hepta-bold">Inicio de Sesion</h1>
        <br>
        <form action="" method="POST" id="form_login">
            {% csrf_token %}
            <!-- username -->
            <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Usuario:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="txtUsuario" name="username" placeholder="nombre de usuario">
                </div>
            </div>
            <!-- Password -->
            <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Contraseña:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" id="txtPassword" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <div class="position-relative">
                        <a href="{% url 'appRegistro:password_reset' %}" class="stretched-link">¿Olvidó su contraseña?</a>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <div class="position-relative">
                        <a href="{% url 'appRegistro:registro' %}" class="stretched-link">¿Eres nuevo? Registrate Aquí.</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

appRegistro/templates/appRegistro/password_reset_form.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block titulo %}Iniciar sesion{% endblock titulo %}
{% block nav_class_login %}active{% endblock nav_class_login %}

{% block content %}
  <h3>¿Olvidó su contraseña?</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p|crispy }}
    <button type="submit">Recuperar</button>
  </form>
{% endblock %}

appRegistro/templates/appRegistro/registro.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Registrar usuario{% endblock titulo %}
{% block content %}
    <div id="titulo-registro" class="subheader">
        <h1 class="hepta-bold">Formulario de Registro</h1>
        <h4 class="hepta">Completa los siguientes datos:</h4>
    </div>
    <div class="form-registro d-flex justify-content-center">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form|crispy }}
            {{ profile_form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
    </div>
{% endblock content %}