appEditorial/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'appEditorial'

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('', views.home),
	url('home/', views.home, name = 'home'),
	url('catalogo/', views.catalogo, name = 'catalogo'),
    url(r'catalogo$', views.catalogo_filtro, name = 'catalogo_filtro'),
    url(r'editar$', views.editar_libros, name = 'editar_libros'),
    url(r'editar_libro$', views.editar_libro, name = 'editar_libro'),
    url(r'eliminar_libro$', views.eliminar_libro, name = 'eliminar_libro'),
    url('autores/', views.autores, name = 'autores'),
    url('about/', views.about, name = 'about'),
    url('contacto/', views.contacto, name = 'contacto'),
    url('gestionLibros/', views.gestionarLibros, name = 'gestionLibros'),
    url('agregar_libro/', views.agregar_libro, name = 'agregar_libro'),
    url('editar_libro/', views.editar_libro, name = 'editar_libro'),
    url('agregar_autor/', views.agregar_autor, name = 'agregar_autor'),
    url('agregar_editorial/', views.agregar_editorial, name = 'agregar_editorial'),
    path('api/libros/', views.API_libros.as_view()),
    path('api/libros/id/<id>/', views.API_libro_por_id.as_view()),
    path('api/libros/titulo/<titulo>/', views.API_libro_por_titulo.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

appRegistro/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'appRegistro'

urlpatterns = [
    url('index/', views.index, name = 'index'),
    url('login/', views.usuario_login, name = 'login'),
    url('logout/', views.usuario_logout, name = 'logout'),
    url('registro/', views.registrar, name = 'registro'),
    url('gestionEditorial/', views.gestionarEditorial, name = 'gestionEditorial'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='recuperacion/password_reset_form.html',
             subject_template_name='recuperacion/password_reset_subject.txt',
             email_template_name='recuperacion/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='recuperacion/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='recuperacion/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='recuperacion/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

editorial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mantenedor/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sicmundus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('appEditorial.urls')),
    path('admin/', admin.site.urls),
    path('ad/', include('appRegistro.urls')),
    url('ad/', include('django.contrib.auth.urls')),
]

appEditorial/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):
    correo = models.EmailField()
    nombre = models.CharField(max_length=50)
    telefono = models.CharField(max_length=12)
    mensaje = models.TextField()

class Autor(models.Model):
	nombre = models.CharField(max_length=50)
	apellido_p = models.CharField(max_length=50)
	apellido_m = models.CharField(max_length=50)
	fecha_nacimiento = models.DateField(auto_now=False, auto_now_add=False)
	foto = models.ImageField(default='/media/placeholder.png', upload_to='autores/')
	def __str__(self):
		return self.nombre+" "+self.apellido_p+" "+self.apellido_m

class Editorial(models.Model):
	nombre = models.CharField(max_length=50)
	logo = models.ImageField(default='/media/placeholder.png', upload_to='editoriales/')
	def __str__(self):
		return self.nombre

class Libro(models.Model):
	titulo = models.CharField(max_length=100)
	fecha_publicacion = models.DateField(auto_now=False, auto_now_add=False)
	portada = models.ImageField(default='/media/placeholder.png', upload_to='libros/')
	precio = models.IntegerField()
	stock = models.IntegerField()
	isbn = models.IntegerField()
	autor = models.ForeignKey('Autor', on_delete='CASCADE')
	editorial = models.ForeignKey('Editorial', on_delete='CASCADE')
	def __str__(self):
		return self.titulo

appEditorial/forms.py
from django.forms import ModelForm
from django import forms
from .models import Contacto, Autor, Editorial, Libro

class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = ['correo', 'nombre', 'telefono', 'mensaje']
        labels = {
            'correo': 'Correo',
            'nombre': 'Nombre',
            'telefono': 'Teléfono',
            'mensaje': 'Mensaje'
        }

class LibroForm(ModelForm):
	class Meta:
		model = Libro
		fields = [ 'titulo', 'fecha_publicacion', 'precio', 'stock', 'isbn', 'autor', 'editorial', 'portada' ]
		widgets = {
			'fecha_publicacion': forms.SelectDateWidget(
				years=(range(2020,1900, -1))
				),
			'isbn': forms.TextInput(),
		}


class AutorForm(ModelForm):
	class Meta:
		model = Autor
		fields = [ 'nombre', 'apellido_p', 'apellido_m', 'fecha_nacimiento', 'foto'  ]
		widgets = {
			'fecha_nacimiento': forms.SelectDateWidget(
				years=(range(2020,1500, -1))
				),
		}

class EditorialForm(ModelForm):
	class Meta:
		model = Editorial
		fields = [ 'nombre', 'logo' ]

appEditorial/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages

from rest_framework import generics, filters, viewsets

from .forms import ContactoForm, LibroForm, AutorForm, EditorialForm
from .models import Contacto, Libro, Autor
from .filters import LibroFilter
from .serializers import LibroSerializer

# Vistas
def home(request):
	return render(request, 'appEditorial/home.html')

def catalogo(request):
    catalogo = Libro.objects.all()
    filtros = LibroFilter(request.GET, queryset=Libro.objects.all())
    return render(
        request, 'appEditorial/catalogo.html', {'catalogo': catalogo}, {'filtros': filtros}
        )
def catalogo_filtro(request):
    filtro = LibroFilter(request.GET, queryset=Libro.objects.all())
    return render(
        request, 'appEditorial/catalogo.html', {'filtros': filtro}
        )

def editar_libros(request):
    filtro = LibroFilter(request.GET, queryset=Libro.objects.all())
    return render(
        request, 'appEditorial/seleccionar_libros.html', {'filtros': filtro}
        )

def autores(request):
    autores = Autor.objects.all()
    return render(request, 'appEditorial/autores.html', {'autores': autores})

def about(request):
    return render(request, 'appEditorial/about.html')

def contacto(request):
    if request.method == "POST":
        form = ContactoForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit = False)
            model_instance.save()
            return redirect('/editorial/contacto')
    else:
        form = ContactoForm()
        return render(request,
            "appEditorial/contacto.html", {'form': form})


def gestionarLibros(request):
    return render(request, 'appEditorial/gestionarLibros.html')


def agregar_libro(request):
    if request.method == "POST":
        form = LibroForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit = False)
            model_instance.save()
            messages.info(request, 'Libro registrado con éxito')
            return HttpResponseRedirect(reverse('appEditorial:agregar_libro'))
        else:
            messages.info(request, 'No se ha podido registrar el libro')
            return HttpResponseRedirect(reverse('appEditorial:agregar_libro'))
    else:
        form = LibroForm()
    return render(request, 'appEditorial/agregarLibro.html',
        {
            'libro_form': form,
        })


def editar_libro(request):
    libro_id = request.GET['id']
    libro = Libro.objects.get(id=libro_id)
    if request.method == "POST":
        form = LibroForm(request.POST, instance=libro)
        if form.is_valid():
            model_instance = form.save(commit = False)
            model_instance.save()
            return HttpResponseRedirect(reverse('appEditorial:editar_libros'))
        else:
            return HttpResponseRedirect(reverse('appEditorial:editar_libros'))
    else:
        form = LibroForm(instance=libro)
        return render(request, 'appEditorial/editar_libro.html',
            {
                'libro_form': form,
            })

def eliminar_libro(request):
    libro_id = request.GET['id']
    libro = Libro.objects.get(id=libro_id)
    libro.delete()
    messages.info(request, 'Libro eliminado correctamente')
    return HttpResponseRedirect(reverse('appEditorial:editar_libros'))

def agregar_autor(request):
    if request.method == "POST":
        form = AutorForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit = False)
            model_instance.save()
            messages.info(request, 'Autor registrado con éxito')
            return HttpResponseRedirect(reverse('appEditorial:agregar_autor'))
        else:
            messages.info(request, 'No se ha podido registrar el autor')
            return HttpResponseRedirect(reverse('appEditorial:agregar_autor'))
    else:
        form = AutorForm()
    return render(request, 'appEditorial/agregarAutor.html',
        {
            'autor_form': form
        })

def agregar_editorial(request):
    if request.method == "POST":
        form = EditorialForm(request.POST)
        if form.is_valid():
            model_instance = form.save(commit = False)
            model_instance.save()
            messages.info(request, 'Editorial registrada con éxito')
            return HttpResponseRedirect(reverse('appEditorial:agregar_editorial'))
        else:
            messages.info(request, 'No se ha podido registrar la editorial')
            return HttpResponseRedirect(reverse('appEditorial:agregar_editorial'))
    else:
        form = EditorialForm()
    return render(request, 'appEditorial/agregarEditorial.html',
        {
            'editorial_form': form
        })

# Las vistas de la api serán sacadas directamente de estas clases

#Todos los libros
class API_libros(generics.ListAPIView):
    serializer_class = LibroSerializer
    queryset = Libro.objects.all()

#Libros filtrados por titulo
class API_libro_por_titulo(generics.ListAPIView):
    serializer_class = LibroSerializer

    def get_queryset(self):
        titulo = self.kwargs['titulo']
        return Libro.objects.filter(titulo=titulo)

#Libros filtrados por id
class API_libro_por_id(generics.ListAPIView):
    serializer_class = LibroSerializer

    def get_queryset(self):
        id = self.kwargs['id']
        return Libro.objects.filter(id=id)

appEditorial/templates/appEditorial/about.html
{% extends 'appEditorial/base.html' %}

{% load staticfiles %}

{% block nav_class_about %}active{% endblock %}

{% block content %}
    <div class="subheader hepta-bold">
        <h1 class="titulo">¿Quiénes somos?</h1>
    </div>
    <div class="parrafo contenedor hepta">
        <p>Somos una editorial que nace en el año 2019, con el deseo de
        contribuir a la difusión de la lectura y la apreciación por los libros. </p>
        <p>Asimismo, queremos fomentar el desarrollo del pensamiento creativo de niños y jóvenes mediante el aporte de diversos colaboradores y autores que ponen a disposición su arduo trabajo.</p>

        <p>Ponemos toda nuestra dedicación en la oferta de nuestro catálogo, cuidando el trabajo de autores e ilustradores. De esta manera, nos aseguramos de ofrecer productos de calidad a todos nuestros destinatarios.</p>

        <p>Somos un equipo que nos une la pasión de la lectura y disfruta con el corazón cada libro que pasa por nuestras manos. Esperamos que cada persona que vea nuestro trabajo se llene de ese sentimiento.</p>
    </div>
    <br>
{% endblock %}}

appEditorial/templates/appEditorial/agregarAutor.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Agregar Autor{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block content %}
	<div class="subheader">
		<h1 class="titulo hepta-bold">Ingresar Autor</h1>
	</div>
    <div class="form-registro d-flex justify-content-center">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ autor_form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
    </div>
{% endblock content %}

appEditorial/templates/appEditorial/agregarEditorial.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Agregar Editorial{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block content %}
	<div class="subheader">
		<h1 class="titulo hepta-bold">Ingresar Editorial</h1>
	</div>
    <div class="form-registro d-flex justify-content-center">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ editorial_form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Registrar</button>
        </form>
    </div>
{% endblock content %}

appEditorial/templates/appEditorial/agregarLibro.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Ingresar libro{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block nav_content %}
    {% include 'appEditorial/base_nav_libros.html' %}
{% endblock nav_content %}
{% block content %}
	<div class="subheader">
		<h1 class="titulo hepta-bold">Ingresar Libro</h1>
	</div>
    <div class="form-registro d-flex justify-content-center">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ libro_form|crispy }}
            <br>
            <button type="submit" onclick="clicked(event, '¿Desea agregar el libro?')"  class="btn btn-primary">Registrar</button>
        </form>
    </div>
{% endblock content %}

appEditorial/templates/appEditorial/autores.html
{% extends 'appEditorial/base.html' %}
{% load staticfiles %}
{% block nav_class_autores %}active{% endblock %}
{% block content %}
    <div class="subheader hepta-bold">
        <h1 class="titulo">Nuestros<br>Autores</h1>
    </div>
    <div class="autores hepta">
        <div class="d-flex flex-wrap justify-content-center">
            <!-- Autor #1 -->
            {% for autor in autores %}
                <div class="d-flex flex-column p-2">
                    <div class="card scale-up-center">
                        <img class="autor card-img-top" src="{{ autor.foto.url }}" alt="Foto del autor {{ autor }} - {{ autor.foto.url }}">
                        <div class="card-body">{{ autor }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

appEditorial/templates/appEditorial/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!--Bootstrap con Jquery -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!--CSS propio-->
        <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
        <title>Editorial Sic Mundus</title>
        <!-- Font awesome -->
        <script src="{% static 'fontawesome/js/all.js' %}"></script>
    </head>
    <body>
        <!-- Header -->
        <header>
            <div class="d-flex flex-wrap header-chico hepta-bold">
                <div class="p-2">
                    <a href="{% url 'appEditorial:home' %}">
                        <img class="logo-header" src="{% static 'img/logo.png' %}" alt="logo--editorial">
                    </a>
                </div>
                <!-- Barra de navegación -->
                <div class="p-2 flex-grow-1">
                    <div class="header-chico">
                        <ul class="nav nav-pills nav-justified" id="menu">
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_home %}{% endblock nav_class_home %}" href="{% url 'appEditorial:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_catalogo %}{% endblock nav_class_catalogo %}" href="{% url 'appEditorial:catalogo_filtro' %}">Catálogo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_autores %}{% endblock nav_class_autores %}" href="{% url 'appEditorial:autores' %}">Autores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_about %}{% endblock nav_class_about %}" href="{% url 'appEditorial:about' %}">Quiénes Somos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block nav_class_contacto %}{% endblock nav_class_contacto %}" href="{% url 'appEditorial:contacto' %}">Contacto</a>
                            </li>
                            <li class="hamburguesa">
                                <a href="javascript:void(0);" class=icon onclick="toggleMenu()"><i class="fas fa-bars fa-3x"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Barra de busqueda y botones con iconos-->
                <div class="nav-busqueda">
                    <form class="form-inline">
                        <div class="barra-iconos">
                            {% if not request.user.is_authenticated %}
                                <a href="{% url 'appRegistro:login' %}" data-toggle="tooltip" title="Inicio de sesión" data-placement="bottom">
                                    <i class="fas fa-user fa-2x boton-nav"></i>
                                </a>
                            {% elif request.user.is_superuser %}
                                <a href="{% url 'appRegistro:index' %}" data-toggle="tooltip" title="Administrar" data-placement="bottom">
                                    <i class="fas fa-user-cog fa-2x boton-nav"></i>
                                </a>
                                <a href="{% url 'appRegistro:logout' %}" data-toggle="tooltip" title="Cerrar Sesion" data-placement="bottom">
                                    <i class="fas fa-power-off fa-2x boton-nav"></i>
                                </a>
                            {% else %}
                                <a href="" data-toggle="tooltip" title="Carro de Compras" data-placement="bottom">
                                    <i class="fas fa-shopping-cart fa-2x boton-nav"></i>
                                </a>
                                <a href="{% url 'appRegistro:logout' %}" data-toggle="tooltip" title="Cerrar Sesion" data-placement="bottom">
                                    <i class="fas fa-power-off fa-2x boton-nav"></i>
                                </a>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </header>
        <div id="contenedor">
            <div id="main">
                {% block content %}

                {% endblock content %}
            </div>
        </div>
        <footer class="d-flex flex-wrap footer">
            <div class="d-flex flex-wrap p-2 logo-footer">
                <img id="logo_footer" src="{% static 'img/logo.png' %}" alt="logo-editorial">
            </div>
            <div class="d-flex flex-row p-2 redes">
                <div><i class="fab fa-facebook-square fa-5x p-2 rrss-logo"></i></div>
                <div><i class="fab fa-instagram fa-5x p-2 rrss-logo"></i></div>
                <div><i class="fab fa-twitter-square fa-5x p-2 rrss-logo"></i></div>
            </div>
        </footer>
        <script src="/js/hamburguesa.js"></script>
    </body>
</html>

appEditorial/templates/appEditorial/base_nav_libros.html
<div class="nav-gestion d-flex justify-content-end">
    <ul class="nav nav-tabs">
        <li id="boton-agregar" class="nav-item">
            <a class="nav-link" href="{% url 'appEditorial:agregar_libro' %}">Agregar Libros</a>
        </li>
        <li id="boton-editar" class="nav-item">
            <a class="nav-link" href="{% url 'appEditorial:editar_libros' %}">Editar y Eliminar Libros</a>
        </li>
    </ul>
</div>

appEditorial/templates/appEditorial/catalogo.html
{% extends 'appEditorial/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block nav_class_catalogo %}active{% endblock nav_class_catalogo %}

{% block content %}
        <div class="subheader hepta-bold">
            <h1 class="titulo">Nuestro<br>Catálogo</h1>
        </div>
        <div class=form-busqueda>
            <form action="" method="GET">
                {{ filtros.form|crispy }}
                <br>
                <input type="submit" value="Buscar"/>
            </form>
        </div>
        <div class="catalogo p-4 nunito">
            <div class="d-flex flex-wrap justify-content-center">
            {% for libro in filtros.qs %}
                <div class="d-flex flex-column p-2">
                    <div class="card">
                        <img class="portada card-img-top" src="{{ libro.portada.url }}" alt="Foto de la portada de {{ libro.titulo }} {{ libro.portada.url }} ">
                        <div class="card-body">
                            <span class="badge badge-titulo">Título</span> {{ libro.titulo }} <br>
                            <span class="badge badge-autor">Autor</span> {{ libro.autor }} <br>
                            <span class="badge badge-precio">Precio</span> {{ libro.precio }}
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        
        <div class="catalogo p-4 nunito">
            <div class="d-flex flex-wrap justify-content-center">
                {% for libro in catalogo %}
                    <div class="d-flex flex-column p-2">
                        <div class="card">
                            <img class="portada card-img-top" src="{{ libro.portada.url }}" alt="Foto de la portada de {{ libro.titulo }} {{ libro.portada.url }} ">
                            <div class="card-body">
                                <span class="badge badge-titulo">Título</span> {{ libro.titulo }} <br>
                                <span class="badge badge-autor">Autor</span> {{ libro.autor }} <br>
                                <span class="badge badge-precio">Precio</span> {{ libro.precio }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <br>
        <script>
        </script>
{% endblock content %}

appEditorial/templates/appEditorial/contacto.html
{% extends 'appEditorial/base.html' %}

{% load staticfiles %}

{% block nav_class_contacto %}active{% endblock %}

{% block content %}
    <div class="subheader hepta-bold">
        <h1 class="titulo">Contacto</h1>
    </div>
    <div class="nunito p-4">
        <form method="POST" id="form-contacto">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Enviar</button>
    </div>

{% endblock %}

appEditorial/templates/appEditorial/editar_libro.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Ingresar libro{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block nav_content %}
    {% include 'appEditorial/base_nav_libros.html' %}
{% endblock nav_content %}
{% block content %}
	<div class="subheader">
		<h1 class="titulo hepta-bold">Ingresar Libro</h1>
	</div>
    <div class="form-registro d-flex justify-content-center">
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ libro_form|crispy }}
            <br>
            <button type="submit" onclick="clicked(event, '¿Desea conservar los cambios {{ libro_form.titulo.value }}?')" class="btn btn-primary">Editar</button>
        </form>
    </div>
{% endblock content %}

appEditorial/templates/appEditorial/gestionarLibros.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block titulo %}Gestionar Libros{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block nav_content %}
    {% include 'appEditorial/base_nav_libros.html' %}
{% endblock nav_content %}

appEditorial/templates/appEditorial/login.html
{% extends 'appEditorial/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="login p-2">
        <form action="" method="POST" id="form_login">
            <!-- correo -->
            <div class="form-group row">
                <label for="txtCorreo" class="col-sm-2 col-form-label">Correo</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="txtCorreo" name="txtCorreo" placeholder="correo@email.com">
                </div>
            </div>
            <!-- Password -->
            <div class="form-group row">
                <label for="txtPassword" class="col-sm-2 col-form-label">Contraseña</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="txtPassword" id="txtPassword" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <div class="position-relative">
                        <a href="#" class="stretched-link">¿Olvidó su contraseña?</a>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <div class="position-relative">
                        <a href="registro" class="stretched-link">¿Eres nuevo? Registrate Aquí.</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

appEditorial/templates/appEditorial/mantenedor_home.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block titulo %}Gestionar Editorial{% endblock titulo %}
{% block nav_class_gestion %}active{% endblock nav_class_gestion %}
{% block content %}
	<div class="d-flex flex-row gestion">
		<div class="p-2 flex-fill nunito-bold libros" onclick="location.href={% url 'appEditorial:gestionLibros' %}">
			Libros <br>
			<span  style="font-size: 72px" >
				<i class="fas fa-book"></i>
			</span>
		</div>
		<div class="p-2 flex-fill nunito-bold autores" onclick="location.href={% url 'appEditorial:agregar_autor' %}">
			Autores <br>
			<span  style="font-size: 72px" >
				<i class="fas fa-pen-fancy"></i>
			</span>
		</div>
		<div class="p-2 flex-fill nunito-bold editoriales" onclick="location.href={% url 'appEditorial:agregar_editorial' %}">
			Editoriales <br>
			<span  style="font-size: 72px" >
				<i class="fas fa-glasses"></i>
			</span>
		</div>
	</div>
{% endblock content %}