appRegistro/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'appRegistro'

urlpatterns = [
    url('index/', views.index, name = 'index'),
    url('login/', views.usuario_login, name = 'login'),
    url('logout/', views.usuario_logout, name = 'logout'),
    url('registro/', views.registrar, name = 'registro'),
    url('gestionEditorial/', views.gestionarEditorial, name = 'gestionEditorial'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='recuperacion/password_reset_form.html',
             subject_template_name='recuperacion/password_reset_subject.txt',
             email_template_name='recuperacion/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='recuperacion/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='recuperacion/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='recuperacion/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

editorial/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mantenedor/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sicmundus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('appEditorial.urls')),
    path('admin/', admin.site.urls),
    path('ad/', include('appRegistro.urls')),
    url('ad/', include('django.contrib.auth.urls')),
]

appRegistro/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class PerfilUsuario(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	run = models.CharField(max_length=20)
	nacimiento = models.DateField(auto_now=False, auto_now_add=False)
	telefono = models.CharField(max_length=50)
	region = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=50)
	comuna = models.CharField(max_length=50)
	vivienda = models.CharField(max_length=50)

	def __str__(self):
		return self.run


appRegistro/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import PerfilUsuario


class PerfilUsuarioForm(ModelForm):
    class Meta():
        model = PerfilUsuario
        fields = [
            'run',
            'nacimiento',
            'telefono',
            'region',
            'ciudad',
            'comuna',
            'vivienda'
        ]
        labels = {
            'run': 'RUN',
            'nacimiento': 'Fecha de Nacimiento',
            'telefono': 'Teléfono',
            'region': 'Región',
            'ciudad': 'Ciudad',
            'comuna': 'Comuna',
            'vivienda': 'Vivienda'
        }
        widgets = {
            'nacimiento': forms.SelectDateWidget(
                years=(range(2020, 1900, -1)))
        }

    def __init__(self, *args, **kwargs):
        super(PerfilUsuarioForm, self).__init__(*args, **kwargs)
        self.fields['run'].widget.attrs.update({'class': 'form-control'})
        self.fields['nacimiento'].widget.attrs.update({'class': 'form-control datepicker'})
        self.fields['telefono'].widget.attrs.update({'class': 'form-control'})
        self.fields['region'].widget.attrs.update({'class': 'form-control'})
        self.fields['ciudad'].widget.attrs.update({'class': 'form-control'})
        self.fields['comuna'].widget.attrs.update({'class': 'form-control'})
        self.fields['vivienda'].widget.attrs.update({'class': 'form-control'})


class RegistrarForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',
            'first_name',
            'last_name'
        ]
        labels = {
            'username': 'Nombre de Usuario',
            'password': 'Contraseña',
            'email': 'Correo',
            'first_name': 'Nombre',
            'last_name': 'Apellido'
        }
        help_texts = {
            'username': ''
        }


    def __init__(self, *args, **kwargs):
        super(RegistrarForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})

appRegistro/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages

from .forms import PerfilUsuarioForm, RegistrarForm
from .models import PerfilUsuario
from appEditorial import templates

# Create your views here.
def index(request):
	return render(request, "appRegistro/index.html")


def usuario_logout(request):
	if request.user.is_superuser:
		logout(request)
		return HttpResponseRedirect(reverse('appRegistro:login'))
	else:
		logout(request)
		return HttpResponseRedirect(reverse('appEditorial:home'))


def usuario_login(request):
	if request.user.is_authenticated:
		if request.user.is_superuser:
			return HttpResponseRedirect(reverse('appRegistro:index'))
		else:
			return HttpResponseRedirect(reverse('appEditorial:home'))
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')
			user = authenticate(username=username, password=password)
			if user:
				if not user.is_active:
					messages.info(request, 'Tu cuenta esta inactiva')
					return HttpResponseRedirect(reverse('appRegistro:login'))
				elif user.is_active and user.is_superuser:
					login(request, user)
					return HttpResponseRedirect(reverse('appRegistro:index'))
				elif user.is_active and not user.is_superuser:
					login(request, user)
					return HttpResponseRedirect(reverse('appEditorial:home'))
			else:
				messages.info(request, 'Clave o Contraseña inválidas')
				return HttpResponseRedirect(reverse('appRegistro:login'))
		else:
			return render(request, 'appRegistro/login.html')


def registrar(request):
	if request.method == 'POST':
		print("Estoy intentando ingresar un usuario")
		user_form = RegistrarForm(data=request.POST)
		profile_form = PerfilUsuarioForm(data=request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			messages.info(request, 'Usuario Registrado Correctamente')
			return HttpResponseRedirect(reverse('appRegistro:login'))
		else:
			return HttpResponse("Datos invalidos.")
	else:
		user_form = RegistrarForm()
		profile_form = PerfilUsuarioForm()

	return render(request, 'appRegistro/registro.html',
					{'user_form': user_form,
					'profile_form': profile_form})


def gestionarEditorial(request):
	return render(request, 'appEditorial/mantenedor_home.html')



appRegistro/templates/recuperacion/password_reset_complete.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Recuperar Contraseña{% endblock titulo %}
{% block nav_class_login %}active{% endblock nav_class_login %}

{% block content %}
<div class="login">
	<p>
		Su nueva contraseña ha sido registrada. Ahora puede 
		<a class="stretched-link" href="{% url 'login' %}">ingresar</a> a su cuenta.
	</p>
</div>
{% endblock %}

appRegistro/templates/recuperacion/password_reset_confirm.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Recuperar Contraseña{% endblock titulo %}
{% block nav_class_login %}active{% endblock nav_class_login %}

{% block content %}
<div class="login">
  {% if validlink %}
    <h3 class="hepta-bold">Cambiar Contraseña</h3>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <br>
      <button class="btn btn-primary" type="submit">
        Cambiar Contraseña
      </button>
    </form>
  {% else %}
    <p>
      El link de reseteo de contraseña fue invalido, probablemente porque ya ha sido usado.
      Por favor vuelva a solicitar un reseteo de contraseña.
    </p>
  {% endif %}
</div>
{% endblock %}

appRegistro/templates/recuperacion/password_reset_done.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% block titulo %}Solicitud cambio contraseña{% endblock titulo %}
{% block content %}
<div class="login">
    <p>
        Si el correo que ingresaste es valido, dentro de poco recibiras un mensaje con las instrucciones para el cambio de contraseña.
    </p>
    <p>
        Si no ha recibido un correo, por favor asegurese de que ha ingresado la direccion con la que se registro. Asegurese tambien de revisar su carpeta
        de spam.
    </p>
</div>
{% endblock %}

appRegistro/templates/recuperacion/password_reset_email.html
{% autoescape off %}
Para comenzar el proceso de cambio de contraseña de tu cuenta Sic Mundus con nombre de usuario: {{ user.get_username }},
haz click en el link de abajo:

{{ protocol }}://{{ domain }}{% url 'appRegistro:password_reset_confirm' uidb64=uid token=token %}

Si el link no funciona, favor de copiar y pegar el URL en una nueva ventana de tu navegador.

Atentamente,
Equipo Sic Mundus
{% endautoescape %}

appRegistro/templates/recuperacion/password_reset_form.html
{% extends 'appRegistro/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block titulo %}Recuperar Contraseña{% endblock titulo %}
{% block nav_class_login %}active{% endblock nav_class_login %}
{% block content %}
<div class="login">
	<form method="post" class="p-2">
        <h3 class="hepta-bold">¿Olvidó su contraseña?</h3>
        <br>
		{% csrf_token %}
		{{ form|crispy }}
		<br>
		<button class="btn btn-primary" type="submit">Recuperar</button>
	</form>
</div>
{% endblock %}